In [1]:
import tensorflow as tf

/Users/yoshidayuusei/.pyenv/versions/3.6.5/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
#ベクトルの計算
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')

c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))#ベクトルごとに計算する

a + b =  [5 7 9]


In [7]:
#行列の計算
a = tf.constant([[1, 2],
                             [3, 4]
                            ])
b = tf.constant([[1],
                             [2]
                            ])
c = tf.matmul(a, b)#行列の掛け算

print(a.shape)
print(b.shape)
print(c.shape)
print("\n")

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

(2, 2)
(2, 1)
(2, 1)


[[1 2]
 [3 4]]
[[1]
 [2]]
[[ 5]
 [11]]


In [11]:
a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a')
#行列をpleceholderで受ける場合は、shapeに型を指定する

with tf.Session() as sess:
    
    print('a = ', sess.run(a, feed_dict={a: [[1, 2]]}))
    print('a = ', sess.run(a, feed_dict={a: [[1, 2], [3, 4]]}))

a =  [[1 2]]
a =  [[1 2]
 [3 4]]
