In [1]:
#入力そうは4つのノード
#隠れそうは３つのノード
#出力層は2つのノード
#活性化関数はシグモイド関数

In [2]:
import numpy as np

In [3]:
num_input = 4
num_hidden =  3
num_output = 2

In [4]:
X = np.random.randn(4)

In [5]:
X

array([ 0.4497978 ,  1.26374301,  0.90571476, -0.25058989])

In [6]:
def shigmoido(h):
    return 1/(1+np.exp(-h))

In [7]:
w_in_h  = np.random.normal(0, scale=0.1, size=(num_input,num_hidden))
print(w_in_h)

[[-0.1499294  -0.07054643  0.09199717]
 [ 0.05019604  0.01638818  0.07336922]
 [ 0.05209597  0.12078035  0.08783069]
 [-0.01970172 -0.06495691  0.07532438]]


In [8]:
w_h_out  = np.random.normal(0, scale=0.1, size=(num_hidden,num_output))
print(w_h_out)

[[ 0.10484082 -0.04769895]
 [-0.05153573 -0.04915598]
 [ 0.13889575  0.01726257]]


In [9]:
h_in = np.dot(X, w_in_h)
h_out = shigmoido(h_in)
print(h_out)

[0.51202721 0.52863087 0.54854014]


In [10]:
out_in = np.dot(h_out, w_h_out)
out_out = shigmoido(out_in)
print(out_out)

[0.52563447 0.4897666 ]


In [ ]:
class  